### PR TITLE
added new methods names

### PR DESCRIPTION
**Pull request by martaint**

### CODE REVIEW

**Review by LuckyMD — CHANGES_REQUESTED** [review]
there will also be a `seurat_rpca`, which just got merged. So that might need to be called Seurat v3 RPCA and the other one "Seurat v3 CCA".

**Comment by martaint** [comment]
> there will also be a `seurat_rpca`, which just got merged. So that might need to be called Seurat v3 RPCA and the other one "Seurat v3 CCA".

I added it! for the metrics file, please remove the underscore in seurat_rpca, that will cause problems in my stringsplit. seuratrpca will work!

**Comment by LuckyMD** [comment]
> I added it! for the metrics file, please remove the underscore in seurat_rpca, that will cause problems in my stringsplit. seuratrpca will work!

@danielStrobl Have you started the runs already? And if not, could you quickly change this? Maybe just use "SeuratRPCA"

**Comment by danielStrobl** [comment]
No, I haven't. Ok I'll adapt that

**Review by LuckyMD — APPROVED** [review]

**Pull request merged**
