### PR TITLE
[WIP] Remove scanpy<1.5 requirement

### PR DESCRIPTION
**Pull request by danielStrobl**
I tried to remove all references to `adata.uns['neighbors']['connectivities']|['distances']` here to make scIB compatible with newer versions of scanpy and anndata.
Still needs testing though.

### CODE REVIEW

**Comment by LuckyMD** [comment]
Is this sth that is testable in your testing pipeline @mumichae ?

**Comment by LuckyMD** [comment]
Also, @danielStrobl... this version now only works for scanpy >= 1.5. could you maybe add a check for neighbors being stored in `.obsp` maybe in the beginning of the metrics function? And then we'd need to reflect scanpy>=1.5 in the environment as well.

**Comment by mumichae** [comment]
The pipeline seems to run through when I upgrade scanpy to version 1.7

**Comment by danielStrobl** [comment]
> Also, @danielStrobl... this version now only works for scanpy >= 1.5. could you maybe add a check for neighbors being stored in `.obsp` maybe in the beginning of the metrics function? And then we'd need to reflect scanpy>=1.5 in the environment as well.

ok, I'll add that

**Comment by mumichae** [comment]
@danielStrobl Are you able to set up the scib-pipeline test in your own environment and get it running?
From what I can see, `anndata==0.7.1` vs `anndata==0.7.5` is what causes the difference here.

**Comment by LuckyMD** [comment]
Does your pipeline test also run the metrics? We would need to test that the metrics work as well. Also kBet, which is affected by this. With the new adaptation from @danielStrobl, maybe also on the old data as input (just test metrics rule).

**Comment by mumichae** [comment]
Yes, the test is end-to-end. I didn't modify any code in the pipeline scripts and things ran through without error. Here are the results of scanpy 1.4.6, anndata 0.7.1 (master) vs. scanpy 1.7, anndata 0.7.5 (scanpy17)
scanpy17-master

**Comment by LuckyMD** [comment]
This looks very good @mumichae! Thanks! Just changes on the stochastic methods (scVI, scANVI), which will deal less well with very small test data. 

As soon as the test for old vs new AnnData object is there, we can merge @danielStrobl !

**Comment by danielStrobl** [comment]
I don't think we explicitly need to check for the correct location, I think scanpy/anndata do that for us.
This is what I get when I import an old file:
```
/home/daniel/.conda/envs/scop/lib/python3.7/site-packages/anndata/compat/__init__.py:182: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
```

**Comment by LuckyMD** [comment]
> I think scanpy/anndata do that for us.

Awesome! Then this is ready for merge from my side. But I think we should give prio to #205. I will approve this for now though.

**Review by LuckyMD — APPROVED** [review]

**Comment by LuckyMD** [comment]
First time GA is being used to check the PR... woop woop ;).

**Comment by mumichae** [comment]
@danielStrobl @LuckyMD I can't seem to find where the scanpy and anndata versions are pinned. Do we need a new PR for that?

**Comment by LuckyMD** [comment]
they're not pinned anymore with this PR...

**Pull request merged**
