### PR TITLE
eval_subset_nn added

### PR DESCRIPTION
**Pull request by mbuttner**
Here's an auxiliary function to compute the number of nearest neighbors in all subsets of a certain label_key (i.e. cell_types).

### CODE REVIEW

**Comment by LuckyMD** [comment]
do you still want this merged? Do you think it should go in metrics? Or is it rather a test function?

**Comment by mbuttner** [comment]
It's rather a test function and I don't mind if you delete the PR.

**Comment by LuckyMD** [comment]
will just close and leave the branch for now

**Comment by mumichae** [comment]
@mbuttner Do we want to integrate this code anywhere or can this branch go?

**Comment by mbuttner** [comment]
Yes, close and delete, please.

**Pull request closed without merging**
