### PR TITLE
Coerce to Csparsematrix for C++ conversion efficiency

### PR DESCRIPTION
**Pull request by scottgigante**

### CODE REVIEW

**Comment by scottgigante** [comment]
@LuckyMD bumping this

**Comment by scottgigante** [comment]
Addresses https://github.com/MarioniLab/scran/issues/70

**Comment by LuckyMD** [comment]
Sorry, haven't gotten around to this. The point about the `2e9` non-zero value limitation... is that sth we need to worry about?

**Comment by LuckyMD** [comment]
2e9 non-zero values would mean 25k genes and 80k cells max. That doesn't really work for single-cell data, no? If you assum 90% dropout that would be 800k cells. Still not really enough for our 1 million cell case. What do you think about a size limitation for when you cast to `dgCmatrix`?

**Comment by scottgigante** [comment]
You're right. Maybe a better solution would be to do this in python.

```
X = adata.X.T
if scipy.sparse.issparse(X):
    if X.nnz > 2**31-1:
        X = X.tocoo()
    else:
        X = X.tocsc()
ro.global_ev['data_mat'] = X
```

That way we avoid dgRMatrix which is terrible, and use dgCMatrix when possible.

**Comment by LuckyMD** [comment]
Could you merge master into this PR? Then I can merge. Looks good now and gives me the same results. We can always troubleshoot if there are storage limitations at some point.

**Review by LuckyMD — APPROVED** [review]

**Comment by LuckyMD** [comment]
no merge conflicts... so all good.

**Comment by scottgigante** [comment]
Thanks!

**Pull request merged**
