### PR TITLE
change adata to adata_tmp in LISI_graph

### PR DESCRIPTION
**Pull request by mbuttner**

### CODE REVIEW

**Comment by LuckyMD** [comment]
Can we test on snakemake using only pancreas (but all metrics) to see if this changes lisi scores?

**Review by LuckyMD — APPROVED** [review]
simple fix, just requires testing if this addresses the bug we found.

**Comment by danielStrobl** [comment]
Screenshot from 2020-10-30 17-31-52
Seems like this doesn't affect our scores, so we don't need to rerun.

**Review by danielStrobl — APPROVED** [review]

**Comment by LuckyMD** [comment]
Nice! So this is probably only an issue for subsetted objects then @Hrovatin! We will merge but will then not rerun fully.

**Pull request merged**
