### PR TITLE
Update to scvi tools again, also scgen which now uses scvi tools

### PR DESCRIPTION
**Pull request by adamgayoso**
This also correctly pipes the hvg argument to be used for scvi-tools models. Not sure what is correct here.

### CODE REVIEW

**Comment by mumichae** [comment]
Hi @adamgayoso ,

Thanks a lot for looking into this. Could you update this PR to the latest main so that we hopefully get a green build?

**Comment by mumichae** [comment]
Thanks!

Just a minor thing, could you also run pre-commit to fix file formatting?
i.e.

```
pre-commit run --all-files 
```

**Comment by LuckyMD** [comment]
@mumichae could we include a pre-commit run into the CI pipeline to automate a check and run of pre-commit?

**Comment by mumichae** [comment]
Pre-commit is included in the CI, so it currently fails

**Comment by mumichae** [comment]
> @mumichae could we include a pre-commit run into the CI pipeline to automate a check and run of pre-commit?

@LuckyMD I'm not quite sure if having Github actions create new commits upon linting errors is such a good idea. This could potentially lead to merge issues when one forgets to pull those commits before creating new commits. It would be easier to have anyone developing to use pre-commit locally and/or have maintainers update syntax formatting to any PR branches (as I did in this case)

**Comment by mumichae** [comment]
Thanks @adamgayoso for adapting these functions. I checked that the code runs through in `scib-pipeline`, so I'm merging this PR.

**Comment by LuckyMD** [comment]
Hmm, git should be smart enough to tell the dev that they are behind the PR head and automatically resolve the merge conflicts if it's only linting, no?

**Pull request merged**
