### PR TITLE
Catch metrics errors

### PR DESCRIPTION
**Pull request by danielStrobl**
Catch metrics errors arising for low quality input.
Not tested yet

### CODE REVIEW

**Comment by LuckyMD** [comment]
I think I would go deeper to catch these errors. Especially a `ValueError` is probably something that is quite generic and so should be caught closer to the source. That being said... we might just set a threshold for the connectivity of the subsetted knn graph.

**Comment by danielStrobl** [comment]
> I think I would go deeper to catch these errors. Especially a `ValueError` is probably something that is quite generic and so should be caught closer to the source. That being said... we might just set a threshold for the connectivity of the subsetted knn graph.

I'm not sure if that's possible, this is the error message that is raised:
```
raise ValueError(f'could not find {k} nearest neighbors in {max_iterations}'
ValueError: could not find 70 nearest neighbors in 26diffusion steps.
 Please increase max_iterations or reduce k.
```

**Comment by LuckyMD** [comment]
Super nice solution now. Very elegant!

**Review by LuckyMD — APPROVED** [review]
This looks super nice! Only maybe collect the new error class definition at the top or bottom of the file.

**Comment by danielStrobl** [comment]
Done!

**Comment by LuckyMD** [comment]
tested and it works?

**Pull request merged**
